# Generated by Django 2.1.1 on 2018-10-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0005_auto_20181002_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avater',
            field=models.ImageField(blank=True, upload_to='avtar/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=420),
        ),
    ]
