# Generated by Django 2.1.1 on 2018-10-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0007_auto_20181003_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avater',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar/%Y/%m'),
        ),
    ]
