# Generated by Django 2.1.1 on 2018-10-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0008_auto_20181003_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.png', upload_to='avatar/%Y/%m'),
        ),
    ]
