# Generated by Django 2.1.1 on 2018-10-05 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0010_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
