# Generated by Django 2.1.1 on 2018-10-06 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grumblr', '0011_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followees',
            field=models.ManyToManyField(related_name='follow_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
