# Generated by Django 2.1.1 on 2018-10-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0014_auto_20181006_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=420, null=True),
        ),
    ]
