# Generated by Django 2.1.1 on 2018-10-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0015_auto_20181006_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', upload_to='avatar/%Y/%m'),
        ),
    ]
